movieproject/movieapp/urls.py
from django.urls import path
from . import views

app_name='movieapp'

urlpatterns = [

    path('',views.index,name="index"),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movieproject/movieproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from movieproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import movie

class Movieforms(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . models import movie
from .forms import Movieforms
# Create your views here.
def index(request):
    cinema=movie.objects.all()
    content={
        'movie_list':cinema,
    }
    return render(request,'index.html',content)
def details(request,movie_id):
    cinema= movie.objects.get(id=movie_id)
    return render(request,'details.html',{'key':cinema})
    #return HttpResponse(f"it's Movie number {movie_id}")

def add(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        cinema=movie(name=name,desc=desc,year=year,img=img )
        cinema.save()
    return render(request,'add.html')

def update(request,id):
    movie_dat=movie.objects.get(id=id)
    formdat=Movieforms(request.POST or None,request.FILES,instance=movie_dat)
    if formdat.is_valid():
        formdat.save()
        return redirect('/')
    return render(request,'edit.html',{'form':formdat,'movie':movie_dat})
def delete (request, id):
    if request.method=='POST':
        Movie=movie.objects.get(id=id)
        Movie.delete()
        return redirect('/')
    return render(request,'delete.html',)

movieproject/templates/add.html
{%  extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter Movie Name ">
    <input type="text" name="desc" placeholder="Enter Movie Description ">
    <input type="number" name="year" placeholder="Enter Movie Year ">
    <input type="file" name="img" >
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
      
      Onlne Movie Shop
    </a>
  </nav>
{% block body %}

{% endblock %}
</body>
</html>

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form  method="post">
    {% csrf_token %}
    Are your Sure you want to delete?
    <input type="submit">

</form>
{% endblock %}

movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{key.img.url}}" width="300" height="280">
        </div>
        <div class="col-md-6">
            <h6>{{key.id}}</h6>
            <h4>{{key.name}}</h4>
            <h4>{{key.desc}}</h4>
            <h4>{{key.year}}</h4>
            <a class="btn btn-warning" href="{% url 'movieapp:update' key.id %}">update</a> <br>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' key.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input  type="submit">

</form>
{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap"  width="100px" height="200px">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.desc}}</p>
                    <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}